/* M11: macro with an iterative do-loop generating rows; rows(3) makes x=1,2,3. */
%macro rows(k);
  %do i = 1 %to &k;
    x = &i; output;
  %end;
%mend;

data nums;
  %rows(3)
run;

title 'Rows generated by a macro loop';
proc print data=nums;
  var x;
run;
