use crate::ast::DatasetRef;
use crate::library::LibraryManager;
use crate::log::LogWriter;
use crate::output::{OutputDestination, TextListing};
use std::collections::HashMap;
use std::path::PathBuf;

/// System options (OPTIONS statement). M1 honors LS=; everything else is
/// parsed and ignored with a WARNING.
pub struct SasOptions {
    pub ls: usize,
    /// FIRSTOBS= : 1-based number of the first observation to read from each
    /// input data set. Default 1.
    pub firstobs: usize,
    /// OBS= : the number of the LAST observation to process (1-based, an upper
    /// bound on the observation count read). `None` = no limit (OBS=MAX).
    pub obs: Option<usize>,
    /// M19.3 — MPRINT : echo each line of code generated by macro expansion to
    /// the log. Default OFF.
    pub mprint: bool,
    /// M19.3 — MLOGIC : echo macro execution decisions (macro entry/exit, %if
    /// conditions, parameter binding) to the log. Default OFF.
    pub mlogic: bool,
    /// M19.3 — SYMBOLGEN : echo each `&symbol` resolution to the log. Default
    /// OFF.
    pub symbolgen: bool,
}

impl Default for SasOptions {
    fn default() -> Self {
        // SAS 9.4 listing default linesize.
        SasOptions {
            ls: 96,
            firstobs: 1,
            obs: None,
            mprint: false,
            mlogic: false,
            symbolgen: false,
        }
    }
}

/// M22.2 — options globales ODS appliquées au rendu des destinations.
///
/// Ces options correspondent aux options système SAS classiques
/// (CENTER/NOCENTER, DATE/NODATE, NUMBER/NONUMBER). En M22.2 elles sont
/// stockées sur la session et exposées aux destinations via `session.ods_options`
/// ; leur application effective au rendu (centrage, ligne de date/numéro de page)
/// arrive en M22.3+. Les valeurs par défaut reproduisent les défauts SAS.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct OdsOptions {
    /// `false` = sortie centrée (défaut SAS) ; `true` = NOCENTER (alignée à
    /// gauche).
    pub nocenter: bool,
    /// `true` = afficher la date (défaut SAS) ; `false` = NODATE.
    pub date: bool,
    /// `true` = numéroter les pages (défaut SAS) ; `false` = NONUMBER.
    pub number: bool,
}

impl Default for OdsOptions {
    fn default() -> Self {
        // Défauts SAS : CENTER, DATE, NUMBER actifs.
        OdsOptions {
            nocenter: false,
            date: true,
            number: true,
        }
    }
}

/// Everything a step needs to execute: libraries, output writers, options.
pub struct Session {
    pub libs: LibraryManager,
    pub log: LogWriter,
    /// Destination de sortie par défaut (M22.1). Auparavant un `ListingWriter`
    /// concret ; désormais un trait object [`OutputDestination`] initialisé à
    /// [`TextListing`] (listing texte byte-identique). Le statement `ODS`
    /// (M22.2+) configurera d'autres destinations via `output_destinations`.
    pub listing: Box<dyn OutputDestination>,
    /// Destinations ODS ouvertes par `ODS <dest> OPEN` (M22.2+), indexées par
    /// nom de destination (UPPERCASE : HTML/RTF/PDF/EXCEL/…). Vide par défaut ;
    /// seul `listing` (texte) est actif tant qu'aucun `ODS` n'a ouvert de
    /// destination supplémentaire.
    pub output_destinations: HashMap<String, Box<dyn OutputDestination>>,
    /// M22.2 — options globales ODS (CENTER/NOCENTER, DATE/NODATE,
    /// NUMBER/NONUMBER), modifiées via [`Session::set_ods_option`] et exposées
    /// aux destinations de sortie. Défauts SAS (centré, date, numéro).
    pub ods_options: OdsOptions,
    /// M22.2 — nom (UPPERCASE) de la destination de sortie courante portée par
    /// `self.listing`. "LISTING" par défaut. Sert à `ODS CLOSE` sans nom.
    pub current_destination: String,
    /// M22.3 — registre `ODS OUTPUT` : capture des tables ODS vers des datasets.
    /// Clé = nom de table ODS en UPPERCASE (ex. "SUMMARY"), valeur = cible
    /// dataset. **Vide par défaut** : tant qu'aucun `ODS OUTPUT` n'a été émis, la
    /// capture est inactive et le listing reste byte-identique. Un proc qui
    /// produit une table ODS connue consulte ce registre via
    /// [`Session::ods_output_target`] ; s'il y trouve sa table, il écrit le
    /// résultat tabulaire comme dataset (en plus du listing).
    pub ods_output_map: HashMap<String, DatasetRef>,
    pub options: SasOptions,
    /// M29.1 — état ODS GRAPHICS (génération d'images PNG/SVG). `enabled=false`
    /// par défaut : tant que `ODS GRAPHICS ON` n'a pas été émis, aucun PROC
    /// graphique ne produit d'image. État GLOBAL persistant (survit aux RUN;).
    pub ods_graphics: crate::ods_graphics::OdsGraphics,
    /// Directory against which relative LIBNAME paths resolve.
    pub base_dir: PathBuf,
    /// _LAST_: most recently created dataset, e.g. "WORK.A" — the default
    /// input of procs without DATA=.
    pub last_dataset: Option<String>,
    /// PROC SQL views (M20.4) : `CREATE VIEW v AS SELECT ...`. Purely in
    /// memory (jamais de parquet) ; clé = nom UPPERCASE de la vue (espace WORK
    /// implicite). Résolues à l'abaissement quand une `FROM` cible une vue.
    pub views: std::collections::HashMap<String, crate::sql::ast::SelectStmt>,
    pub deterministic: bool,
    /// User-defined format catalog (populated by PROC FORMAT).
    pub format_catalog: crate::formats::FormatCatalog,
    /// Processeur macro de la session (M11) : table des symboles `%let`/`&var`.
    /// Sous le build par défaut c'est une identité pure (cf. `MacroEngine`).
    pub macro_engine: crate::preprocess::MacroEngine,
    /// Opt-in : autorise le fast-path vectorisé des étapes DATA simples
    /// (`datastep::fastpath`). OFF par défaut — le chemin ligne-à-ligne reste
    /// la référence ; le fast-path ne s'active que pour les étapes que
    /// `fastpath::eligible` prouve équivalentes.
    pub vectorize: bool,
    /// CALL EXECUTE (M15.6) : file de code SAS produit par `call execute(...)`
    /// pendant une étape DATA, mis en attente pour exécution APRÈS l'étape.
    /// L'exécuteur (`executor::exec_data_step`) draine cette file et rejoue le
    /// code concaténé comme un programme SAS à part entière, une fois l'étape
    /// terminée (sémantique SAS : les instructions CALL EXECUTE s'exécutent
    /// après le RUN de l'étape qui les a générées).
    pub call_execute_queue: Vec<String>,
    /// Test-only (M17.1) : instantané des objets hash de la DERNIÈRE étape DATA
    /// exécutée (nom UPPERCASE → objet final). Peuplé par `datastep::execute`
    /// sous `cfg(test)` pour observer keys/data_vars/options/defined depuis les
    /// tests unitaires (les méthodes find/add qui exposeraient l'état arrivent
    /// en M17.2). Aucun coût ni champ en build de production.
    #[cfg(test)]
    pub debug_hashes: std::collections::HashMap<String, crate::datastep::HashObject>,
    /// M21.1 — PROC PRINTTO : destination de redirection du LOG.
    /// `None` = destination par défaut (LogWriter interne).
    /// v1 : stocké mais pas encore routé (routage différé à M22 ODS).
    pub printto_log: Option<std::path::PathBuf>,
    /// M21.1 — PROC PRINTTO : destination de redirection du LISTING (PRINT).
    /// `None` = destination par défaut (ListingWriter interne).
    /// v1 : stocké mais pas encore routé (routage différé à M22 ODS).
    pub printto_print: Option<std::path::PathBuf>,
}

impl Session {
    pub fn new(
        work_dir: Option<PathBuf>,
        base_dir: PathBuf,
        deterministic: bool,
    ) -> crate::error::Result<Self> {
        let options = SasOptions::default();
        // M19.2 : le processeur macro résout les chemins relatifs de
        // `%include 'fichier';` contre le répertoire de base de la session
        // (même base que LIBNAME/INFILE). `SASAUTOS` reste vide par défaut.
        let mut macro_engine = crate::preprocess::MacroEngine::new(deterministic);
        macro_engine.set_include_base_dir(base_dir.clone());
        Ok(Session {
            libs: LibraryManager::new(work_dir)?,
            log: LogWriter::new(deterministic),
            listing: Box::new(TextListing::new(options.ls)),
            output_destinations: HashMap::new(),
            ods_options: OdsOptions::default(),
            current_destination: "LISTING".to_string(),
            ods_output_map: HashMap::new(),
            options,
            ods_graphics: crate::ods_graphics::OdsGraphics::new(base_dir.clone()),
            base_dir,
            last_dataset: None,
            views: std::collections::HashMap::new(),
            deterministic,
            format_catalog: crate::formats::FormatCatalog::default(),
            macro_engine,
            vectorize: false,
            call_execute_queue: Vec::new(),
            #[cfg(test)]
            debug_hashes: std::collections::HashMap::new(),
            printto_log: None,
            printto_print: None,
        })
    }

    /// Résout un chemin de fichier externe (INFILE/FILE, PROC IMPORT/EXPORT) :
    /// absolu → tel quel ; relatif → joint à `base_dir` (le répertoire de
    /// travail de la session, comme pour les chemins LIBNAME). Garantit un
    /// comportement cohérent et déterministe (les fixtures relatives résolvent
    /// sous le tempdir du harnais, pas sous le CWD du processus).
    pub fn resolve_path(&self, path: &str) -> PathBuf {
        let p = PathBuf::from(path);
        if p.is_absolute() {
            p
        } else {
            self.base_dir.join(p)
        }
    }

    /// M22.2 — ouvre une destination ODS.
    ///
    /// La destination « courante » de la session reste toujours
    /// `self.listing: Box<dyn OutputDestination>` (le défaut texte ou la
    /// dernière destination ouverte). Ouvrir `listing` réinstalle la
    /// destination texte par défaut ; ouvrir une autre destination la pose
    /// comme `listing` courant ET l'enregistre dans `output_destinations`
    /// (indexée par nom UPPERCASE) pour qu'`ODS CLOSE` puisse la retrouver.
    ///
    /// Invariant : la LINESIZE de la session est propagée à la nouvelle
    /// destination pour préserver la cohérence de l'en-tête de page. Le nom de
    /// la destination courante est mémorisé dans `current_destination` afin que
    /// `ODS CLOSE` (sans nom) sache quoi fermer.
    pub fn open_destination(&mut self, name: &str, mut dest: Box<dyn OutputDestination>) {
        let key = name.to_ascii_uppercase();
        dest.set_ls(self.options.ls);
        // La destination courante de la session reste toujours `self.listing` ;
        // on y installe la destination demandée et on note son nom.
        self.listing = dest;
        self.current_destination = key;
    }

    /// M22.2 — ferme une destination ODS nommée.
    ///
    /// Si la destination fermée est la destination courante (ou `LISTING`), on
    /// rétablit le listing texte par défaut comme destination courante. Une
    /// destination supplémentaire enregistrée (M22.3+) est retirée du registre.
    ///
    /// M22.4 : AVANT de remplacer la destination courante, appelle `finalize()`
    /// sur elle. Si `finalize()` renvoie `Some((path, html))`, écrit le fichier
    /// sur disque et émet une NOTE dans le log.
    pub fn close_destination(&mut self, name: &str) {
        let key = name.to_ascii_uppercase();
        self.output_destinations.remove(&key);
        // Fermer la destination courante (ou explicitement LISTING) → revenir au
        // listing texte par défaut byte-identique.
        if key == "LISTING" || key == self.current_destination {
            // M23 : finaliser la destination courante avant de la remplacer.
            // Formats binaires (Excel, PDF) d'abord, puis formats texte (HTML, RTF).
            if let Some((path, bytes)) = self.listing.finalize_to_bytes() {
                let label = self.listing.dest_type_label();
                let file_name = path
                    .file_name()
                    .and_then(|n| n.to_str())
                    .unwrap_or("output")
                    .to_string();
                match std::fs::write(&path, &bytes) {
                    Ok(()) => {
                        self.log.note(&format!("Writing {} file: {}", label, file_name));
                    }
                    Err(e) => {
                        self.log.note(&format!(
                            "WARNING: Could not write {} file {}: {}",
                            label, file_name, e
                        ));
                    }
                }
            } else if let Some((path, content)) = self.listing.finalize() {
                let label = self.listing.dest_type_label();
                let file_name = path
                    .file_name()
                    .and_then(|n| n.to_str())
                    .unwrap_or("output.html")
                    .to_string();
                match std::fs::write(&path, &content) {
                    Ok(()) => {
                        self.log.note(&format!("Writing {} file: {}", label, file_name));
                    }
                    Err(e) => {
                        self.log.note(&format!(
                            "WARNING: Could not write {} file {}: {}",
                            label, file_name, e
                        ));
                    }
                }
            }
            self.listing = Box::new(TextListing::new(self.options.ls));
            self.current_destination = "LISTING".to_string();
        }
    }

    /// M22.3 — enregistre des mappings `ODS OUTPUT table=ds`. Le nom de table
    /// ODS est stocké en UPPERCASE (matching insensible à la casse). Un mapping
    /// pour une table déjà enregistrée écrase l'ancien (sémantique SAS : le
    /// dernier `ODS OUTPUT` gagne).
    pub fn set_ods_output(&mut self, mappings: &[(String, DatasetRef)]) {
        for (table, dref) in mappings {
            self.ods_output_map
                .insert(table.to_ascii_uppercase(), dref.clone());
        }
    }

    /// M22.3 — purge tous les mappings `ODS OUTPUT` (équivalent
    /// `ODS OUTPUT CLOSE ;`). Après cet appel la capture est de nouveau inactive
    /// et le listing redevient byte-identique au comportement par défaut.
    pub fn clear_ods_output(&mut self) {
        self.ods_output_map.clear();
    }

    /// M22.3 — renvoie la cible dataset enregistrée pour une table ODS donnée
    /// (matching insensible à la casse), ou `None` si aucune capture n'est
    /// active pour cette table. Les procs consultent cette méthode AVANT
    /// d'écrire une table capturée.
    pub fn ods_output_target(&self, table: &str) -> Option<DatasetRef> {
        self.ods_output_map.get(&table.to_ascii_uppercase()).cloned()
    }

    /// M22.2 — applique une option globale ODS (CENTER/NOCENTER, DATE/NODATE,
    /// NUMBER/NONUMBER) à la session. Renvoie `true` si `name` est reconnue.
    pub fn set_ods_option(&mut self, name: &str) -> bool {
        match name.to_ascii_lowercase().as_str() {
            "center" => {
                self.ods_options.nocenter = false;
                true
            }
            "nocenter" => {
                self.ods_options.nocenter = true;
                true
            }
            "date" => {
                self.ods_options.date = true;
                true
            }
            "nodate" => {
                self.ods_options.date = false;
                true
            }
            "number" => {
                self.ods_options.number = true;
                true
            }
            "nonumber" => {
                self.ods_options.number = false;
                true
            }
            _ => false,
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::output::{HtmlDestination, TextListing};

    fn new_session() -> Session {
        let tmp = std::env::temp_dir();
        Session::new(None, tmp, true).expect("session")
    }

    #[test]
    fn default_ods_options_are_sas_defaults() {
        let s = new_session();
        assert!(!s.ods_options.nocenter);
        assert!(s.ods_options.date);
        assert!(s.ods_options.number);
    }

    #[test]
    fn set_ods_option_flags() {
        let mut s = new_session();
        assert!(s.set_ods_option("nocenter"));
        assert!(s.ods_options.nocenter);
        assert!(s.set_ods_option("center"));
        assert!(!s.ods_options.nocenter);

        assert!(s.set_ods_option("nodate"));
        assert!(!s.ods_options.date);
        assert!(s.set_ods_option("date"));
        assert!(s.ods_options.date);

        assert!(s.set_ods_option("nonumber"));
        assert!(!s.ods_options.number);
        assert!(s.set_ods_option("NUMBER"));
        assert!(s.ods_options.number);

        // Option inconnue → false, pas de modification.
        assert!(!s.set_ods_option("frobnicate"));
    }

    #[test]
    fn open_listing_keeps_current() {
        let mut s = new_session();
        // La destination courante par défaut est un listing texte avec LS=96.
        assert_eq!(s.listing.ls(), 96);
        s.open_destination("listing", Box::new(TextListing::new(96)));
        assert_eq!(s.listing.ls(), 96);
        // Aucune destination additionnelle enregistrée.
        assert!(s.output_destinations.is_empty());
    }

    #[test]
    fn open_html_becomes_current() {
        let mut s = new_session();
        s.open_destination("html", Box::new(HtmlDestination::new(96)));
        // HTML est la destination courante : son rendu mémoire est vide (stub),
        // et son nom est mémorisé.
        assert_eq!(s.current_destination, "HTML");
        assert_eq!(s.listing.into_string(), "");
    }

    #[test]
    fn close_html_restores_text_listing() {
        let mut s = new_session();
        s.open_destination("html", Box::new(HtmlDestination::new(96)));
        s.close_destination("html");
        assert_eq!(s.current_destination, "LISTING");
        // Le listing texte par défaut redevient la destination courante :
        // un write_line est rendu verbatim.
        s.listing.write_line("hello");
        assert_eq!(s.listing.into_string(), "hello\n");
    }

    /// M22.4 — close_destination avec un fichier cible écrit le HTML sur disque.
    #[test]
    fn close_html_with_file_writes_document() {
        use crate::output::HtmlDestination;

        let tmp_file = std::env::temp_dir().join("sas_test_close_html.html");
        // Nettoyer une éventuelle exécution précédente.
        let _ = std::fs::remove_file(&tmp_file);

        let mut s = new_session();
        s.open_destination(
            "html",
            Box::new(HtmlDestination::with_file(96, tmp_file.clone())),
        );
        // Écrire une table connue via la destination courante.
        s.listing.write_table(
            &["Name".into(), "Score".into()],
            &[crate::output::Align::Left, crate::output::Align::Right],
            &[vec!["Alice".into(), "42".into()]],
        );
        // Fermer → doit écrire le fichier + NOTE + rétablir TextListing.
        s.close_destination("html");

        // La destination est redevenue un TextListing.
        assert_eq!(s.current_destination, "LISTING");
        s.listing.write_line("after");
        assert_eq!(s.listing.into_string(), "after\n");

        // Le fichier HTML existe et contient la table + une valeur connue.
        assert!(tmp_file.exists(), "fichier HTML non créé");
        let content = std::fs::read_to_string(&tmp_file).expect("lecture fichier");
        assert!(content.contains("<table"), "balise <table absente");
        assert!(content.contains("Alice"), "valeur Alice absente");
        assert!(content.contains("42"), "valeur 42 absente");
        assert!(content.contains("<!DOCTYPE html>"), "DOCTYPE manquant");

        // Nettoyer.
        let _ = std::fs::remove_file(&tmp_file);
    }
}
